---
- name: Get list of clusters in Rancher
  uri:
    url: "{{ rancher_api_url }}/v3/clusters"
    method: GET
    validate_certs: false
    return_content: true
    headers:
      Authorization: "Bearer {{ rancher_token }}"
  register: clusters_output

- name: Filter only active clusters that's not ID local
  set_fact:
    cluster_list: "{{ clusters_output | json_query(cquery) }}"
  vars:
    cquery: "*.data[?id!='local' && state=='active'].id"

- name: Download kubeconfig file to directory
  uri:
    url: "{{ rancher_api_url }}/v3/clusters/{{ item }}?action=generateKubeconfig"
    method: POST
    validate_certs: false
    return_content: true
    headers:
      Authorization: "Bearer {{ rancher_token }}"
  register: kubeconfig_results
  with_items:
    "{{ cluster_list }}"

- name: Make kubeconfig storage directory root
  file:
    path: "{{ kubeconfig_dir_root }}"
    mode: '0750'
    state: directory

- name: Make kubeconfig storage directory
  file:
    path: "{{ kubeconfig_dir }}"
    mode: '0750'
    state: directory

- name: Store cluster kubeconfigs in storage directory
  copy:
    content: "{{ item.json.config }}"
    dest: "{{ kubeconfig_dir }}/kubeconfig_{{ item.item }}"
    mode: "0700"
  with_items: "{{ kubeconfig_results.results }}"
