---
- name: Get list of all RKE Clusters
  uri:
    url: "{{ rancher_api_url }}/v3/clusters"
    method: GET
    validate_certs: false
    return_content: true
    headers:
      Authorization: "Bearer {{ rancher_token }}"
  register: clusters_output

- name: Filter only active clusters whose ID is not local
  set_fact:
    cluster_list: "{{ clusters_output | json_query(cquery) }}"
  vars:
    cquery: "*.data[?id!='local' && state=='active'].id"

- name: Obtain kubeconfig for each cluster
  uri:
    url: "{{ rancher_api_url }}/v3/clusters/{{ item }}?action=generateKubeconfig"
    method: POST
    validate_certs: false
    return_content: true
    headers:
      Authorization: "Bearer {{ rancher_token }}"
  register: kubeconfig_results
  with_items:
    "{{ cluster_list }}"
  no_log: "{{ disable_log_msg }}"

- name: Create kubeconfig storage directory root
  file:
    path: "{{ kubeconfig_dir_root }}"
    mode: '0750'
    state: directory

- name: Create kubeconfig storage directory
  file:
    path: "{{ kubeconfig_dir }}"
    mode: '0750'
    state: directory

- name: Write cluster kubeconfigs to storage directory
  copy:
    content: "{{ item.json.config }}"
    dest: "{{ kubeconfig_dir }}/kubeconfig_{{ item.item }}"
    mode: "0700"
  with_items: "{{ kubeconfig_results.results }}"
  no_log: "{{ disable_log_msg }}"
